### PR TITLE
delete hosts before deleting sym systematic

### PR DESCRIPTION
**Pull request by K-Johnson-Horrigan**

### CODE REVIEW

**Review by emilydolson — COMMENTED** [review]
Oh, wow, this is a way better solution to #190 than any of the ones I came up with! Looks great! 

If it's not too much trouble, adding a small test that enforces that the phylogeny gets destructed properly and doesn't seg-fault might be worthwhile.

**Comment by anyaevostinar** [comment]
@K-Johnson-Horrigan Would it be possible to do the small test that Emily mentioned? Probably just creating the world with phylogeny on and then deleting it and making sure it doesn't crash would work?

**Review by anyaevostinar — CHANGES_REQUESTED** [review]
Let's try to do the test that is mentioned in the comment thread to catch this kind of error in the future

**Review by anyaevostinar — APPROVED** [review]
Great job!

**Pull request merged**
